name: actions test
on:
  push:
    branches:
      - actions
jobs:
  build-teste:
    name: ğŸ‰ Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Test Action
        run: TestCreate
        with:
          path: src\test\java\com\br\cooapi\brand
